version: '3'
services:
  web1:
    image: prashanth1211/sit323-737-2023-t1-prac5p
    ports:
      - "8081:80"
    restart: on-failure
    networks:
      coffee:
        ipv4_address: 192.168.92.15
  web2:
    image: sit323-737-2023-t1-prac5p
    ports:
      - "8082:80"
    restart: on-failure
    networks:
      coffee:
        ipv4_address: 192.168.92.21
networks:
  coffee:
    ipam:
      driver: default
      config:
        - subnet: "192.168.92.0/24"





